name: barleyhill
favicon: null
layout_spectrum: 0.45237
typography_spectrum: 0.16639217897318304
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fff3e4'
    - '#491d16'
    - '#937a78'
    - '#d76e00'
    - '#e8b24e'
  brandStrength: 0.8125
  lightness: 0.9484869495499879
  saturation: 0.8267482230439782
  rhythmicContrast: 0.21960884449072182
purpose: []
